---
name: My Neighbourhood
capabilities:
- gps

bbver: 5.0
sdk: "/opt/local/lib/ruby/gems/1.8/gems/rhodes-2.2.3"
sdkversion: 2.2.3
applog: rholog.txt
version: 1.0
vendor: rhomobile
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone:
  empulator: 4.0.2
  sdk: iphonesimulator4.0
  configuration: Debug
  codesignidentity: ""
  entitlements: ""
  BundleIdentifier: com.accenture.iphone.myneighbourhood
  BundleURLScheme: myneighbourhood
android:
  mapping: yes
  apikey: "0huG34HA0SCUkQz7qbLgG2LsZGrZxb5VPqAMnRQ"
  version: 2.2

extensions: 
- json
- uri
