--- 
extensions: 
- json
- uri
name: NYCAppsPOC
capabilities: 
- gps
bbver: 5.0
android: 
  version: 2.1
  apikey: 0CkzmD4eTF4jpcc5I5s1IcVEJ_X-9AZ9gqNiflQ
  mapping: true
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.2.6
applog: rholog.txt
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.2.6
iphone: 
  BundleURLScheme: myneighbourhood
  BundleIdentifier: com.accenture.iphone.myneighbourhood
  sdk: iphonesimulator4.0
  entitlements: ""
  codesignidentity: ""
  configuration: Debug
  empulator: 4.0.2
